"""Add uuid, link, price columns

Revision ID: 248fd3c56329
Revises: 8c0fe552f543
Create Date: 2023-11-08 16:09:10.802970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248fd3c56329'
down_revision: Union[str, None] = '8c0fe552f543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('uuid', postgresql.UUID(), nullable=True, as_uuid=True))
    op.add_column('gift', sa.Column('link', sa.String(length=256), nullable=True))
    op.add_column('gift', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift', 'price')
    op.drop_column('gift', 'link')
    op.drop_column('gift', 'uuid')
    # ### end Alembic commands ###
