"""Add option for uuid field

Revision ID: 41f964985bde
Revises: 51875dda0b52
Create Date: 2023-11-08 16:11:04.487847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f964985bde'
down_revision: Union[str, None] = '51875dda0b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
