"""Add comment to Gift

Revision ID: 8c0fe552f543
Revises: 4b02fe0a5899
Create Date: 2023-11-08 01:10:35.316961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0fe552f543'
down_revision: Union[str, None] = '4b02fe0a5899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift', 'comment')
    # ### end Alembic commands ###
